"""GATE 6b — public receipt verification (Feature 3).

Phase 6 already anchors every commitment as a signed, on-chain-confirmed receipt. This gate
proves the read-only, public surface built on top of it: a client who received a quote can hit
`/r/{receipt_id}` and see exactly what was committed, without any authentication and without
CONCIERGE handing out a general receipts-read capability. Every receipt anchored here is real —
the SAME `receipts.anchor()` GATE 6 proves, spending the same real (tiny) mainnet gas — because
this feature is a view over Phase 6's real data, never a separate, potentially-stale copy of it.
"""

from __future__ import annotations

import uuid

from fastapi.testclient import TestClient

from . import app as app_module
from . import db, engine, onboarding, receipts, store
from . import verify_phase6 as p6

PROSPECT = "priya.raman@example.com"


def _onboard(business: str) -> uuid.UUID:
    session = onboarding.start(p6.SPA["description"])
    for key, value in p6.SPA["answers"].items():
        session.answer(key, value)
    tenant_id, _, _ = onboarding.finalise(
        session, business_name=business,
        owner_email=f"owner@{uuid.uuid4().hex[:8]}.example",
        owner_wallet="0x" + uuid.uuid4().hex[:40].ljust(40, "0"))
    return tenant_id


def _converse(tenant_id, messages):
    outcomes = []
    with db.tenant_session(tenant_id) as cur:
        tenant = store.get_tenant(cur)
        thread = engine.open_thread(cur, tenant, engine.Inbound(
            body="", from_address=PROSPECT, external_ref=f"ref-{uuid.uuid4().hex[:8]}"))
        for body in messages:
            outcome = engine.step(cur, tenant, thread, engine.Inbound(
                body=body, from_address=PROSPECT, from_name="Priya Raman"))
            thread = outcome.thread
            outcomes.append(outcome)
    return outcomes


def run(r) -> None:
    db.migrate()
    client = TestClient(app_module.app)

    tenant_a = _onboard("Halcyon Rooms Verify6b-A")
    tenant_b = _onboard("Halcyon Rooms Verify6b-B")

    # ---- 1. a real quote receipt, anchored for real (same call GATE 6 proves)
    quote_outs = _converse(tenant_a, ["Hi, how much is a deep tissue massage?"])
    quote_receipt = quote_outs[0].receipt
    with db.tenant_session(tenant_a) as cur:
        anchored = receipts.anchor(cur, quote_receipt)
    r.check(
        "A real receipt from a real conversation is anchored for real before this gate touches it",
        bool(anchored.signature) and bool(anchored.xlayer_tx),
        "Feature 3 is a read-only view — it creates no data of its own. This anchor is the exact\n"
        "same call GATE 6 proves end to end (signature + on-chain confirmation); GATE 6b starts\n"
        "from a receipt that is already real and already anchored, and only checks what the\n"
        "public page does with it.",
        f"| receipt_id = {anchored.receipt_id}\n"
        f"| xlayer_tx  = {anchored.xlayer_tx}",
    )

    # ---- 2. the public page shows exactly what's in the database — nothing more, nothing stale
    resp = client.get(f"/r/{anchored.receipt_id}")
    body = resp.text
    r.check(
        "The public page displays the committed terms, matching the on-chain data exactly",
        (resp.status_code == 200
         and "Deep tissue massage" in body
         and str(anchored.xlayer_tx) in body
         and f"x-layer/evm/tx/{anchored.xlayer_tx}" in body
         and "Verified" in body and "NOT VERIFIED" not in body
         and "£85" in body),
        "The page is generated by `receipts.public_view`, which reads the row through the same\n"
        "`public_receipt` SQL function the app uses in production — never a cache, never a copy.\n"
        "The service name and price are the exact words CONCIERGE sent the prospect\n"
        "(`decision['reply_sent']`), the transaction hash on the page is the same one anchored\n"
        "on X Layer mainnet in check 1, and the integrity line is genuinely computed by\n"
        "recomputing the content hash from the stored decision, not asserted.",
        f"| GET /r/{anchored.receipt_id} -> {resp.status_code}\n"
        f"| tx hash on page matches anchored tx: {str(anchored.xlayer_tx) in body}\n"
        f"| explorer link present: {f'x-layer/evm/tx/{anchored.xlayer_tx}' in body}",
    )

    # ---- 3. ATTACK — a non-existent receipt id returns a clean "not found", nothing else
    ghost_id = uuid.uuid4()
    resp_ghost = client.get(f"/r/{ghost_id}")
    r.check(
        "ATTACK — a well-formed but non-existent receipt id returns a clean 404, no internal detail",
        resp_ghost.status_code == 404 and "not found" in resp_ghost.text.lower()
        and "Traceback" not in resp_ghost.text and "Halcyon" not in resp_ghost.text,
        "A syntactically valid UUID that simply does not exist in the table. The response carries\n"
        "no hint of what data model exists behind it, no stack trace, nothing that would help\n"
        "someone enumerate real ids.",
        f"| GET /r/{ghost_id} -> {resp_ghost.status_code}",
    )

    # ---- 4. ATTACK — a malformed id is refused exactly the same way, never a 500
    resp_bad = client.get("/r/not-a-real-uuid-at-all")
    r.check(
        "ATTACK — a malformed id is refused with the same clean 404, never a server error",
        resp_bad.status_code == 404 and "not found" in resp_bad.text.lower(),
        "`db.get_public_receipt` catches the UUID parse failure itself and returns None — the\n"
        "route never sees an exception to leak in a 500 response. Malformed input is exactly as\n"
        "unrevealing as a well-formed id that happens not to exist (check 3).",
        f"| GET /r/not-a-real-uuid-at-all -> {resp_bad.status_code}",
    )

    # ---- 5. ATTACK — an internal-only receipt (a floor breach) is never shown, even by its real id
    breach_outs = _converse(tenant_a, ["How much is a deep tissue massage?", "I can only do 55"])
    breach_receipt = breach_outs[1].receipt
    with db.tenant_session(tenant_a) as cur:
        breach_anchored = receipts.anchor(cur, breach_receipt)
    resp_breach = client.get(f"/r/{breach_anchored.receipt_id}")
    r.check(
        "ATTACK — a floor-breach receipt is never shown publicly, even by its own real, anchored id",
        (resp_breach.status_code == 404 and "not found" in resp_breach.text.lower()
         and "70" not in resp_breach.text and "72.25" not in resp_breach.text
         and breach_anchored.decision.get("within_rules") is False),
        "This receipt is completely real — it exists, it is signed, it is anchored on-chain,\n"
        "exactly like the quote receipt in check 1. But its `action` ('floor_breach') is not in\n"
        "`receipts.PUBLIC_ACTIONS`, because its `decision.detail` carries the tenant's exact\n"
        "floor and discount-cap figures — internal guardrail reasoning, never meant for a public\n"
        "page. It renders identically to a receipt that does not exist at all.",
        f"| GET /r/{breach_anchored.receipt_id} -> {resp_breach.status_code}\n"
        f"| this receipt's within_rules: {breach_anchored.decision.get('within_rules')}\n"
        f"| this receipt's floor detail (never shown): "
        f"{breach_anchored.decision.get('detail', {}).get('floor')}",
    )

    # ---- 6. ISOLATION — two tenants' own receipts never cross, even fetched back to back
    quote_b_outs = _converse(tenant_b, ["Hi, how much is a deep tissue massage?"])
    resp_b = client.get(f"/r/{quote_b_outs[0].receipt.receipt_id}")
    r.check(
        "ISOLATION — each tenant's receipt page shows only that tenant's own commitment",
        ("Verify6b-A" in body and "Verify6b-B" not in body   # check-1's page (tenant A)
         and "Verify6b-B" in resp_b.text and "Verify6b-A" not in resp_b.text),
        "The receipt_id is the sole scope (no tenant context is ever resolved for this route), so\n"
        "there is no shared session or cache that could bleed one tenant's page into another's.\n"
        "Tenant A's page names only Halcyon Rooms Verify6b-A; tenant B's names only -B.",
        f"| tenant A's page mentions -B: {'Verify6b-B' in body}\n"
        f"| tenant B's page mentions -A: {'Verify6b-A' in resp_b.text}",
    )

    r.note(
        "What this feature is NOT",
        "No new data is written by any check above beyond the receipts GATE 6's own anchoring\n"
        "flow already creates. `public_receipt` and `receipts.public_view` are read-only; there\n"
        "is no route that lists receipts, and no route takes anything but a single opaque id.",
        "",
    )
